/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./components/BottomNav.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PageWrapper: typeof import('./components/PageWrapper.vue')['default']
  }
}
