/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./components/BottomNav.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
  }
}
