/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/achievements/index" |
  "/pages/cooking-assistant/index" |
  "/pages/diary/index" |
  "/pages/food-detail/index" |
  "/pages/food-result/index" |
  "/pages/messages/index" |
  "/pages/onboarding/body-metrics" |
  "/pages/onboarding/index" |
  "/pages/onboarding/login" |
  "/pages/onboarding/register" |
  "/pages/profile/index" |
  "/pages/recipe-detail/index" |
  "/pages/scan/index" |
  "/pages/scan-fail/index" |
  "/pages/shopping-list/index" |
  "/pages/splash/index" |
  "/pages/wiki/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/scan/index" | "/pages/diary/index" | "/pages/wiki/index" | "/pages/profile/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
