export { useAuth } from './useAuth'
export { useNutrition } from './useNutrition'
export { useFoodRecognition } from './useFoodRecognition'
export { useDiary } from './useDiary'
export { useDashboard } from './useDashboard'
export { useAnalysis } from './useAnalysis'
export { useChat } from './useChat'
export { useFavorites } from './useFavorites'
export { useCommunity } from './useCommunity'
export { useGamification } from './useGamification'
export { setupRouteGuard, isProtectedRoute } from './useRouteGuard'

// 导出相关类型
export type { TimeRange, AISuggestion, NutritionDistribution, DayCalorieData } from './useAnalysis'
export type { UIMessage } from './useChat'
export type { Favorite, FavoriteType } from './useFavorites'
export type { Post, Comment, UserInfo } from './useCommunity'
export type { Achievement } from './useGamification'
